# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TorchgeoClassification
                                 A QGIS plugin
 Classify your aerial or satellite images with torchgeo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-26
        copyright            : (C) 2025 by Ahmet Firat Karaoglu
        email                : firat.karaoglu@tum.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TorchgeoClassification class from file TorchgeoClassification.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .torchgeo_classification import TorchgeoClassification
    return TorchgeoClassification(iface)
